[[DGGRID7]]
arch = "aarch64"
git-tree-sha1 = "34e5dc3c5ae0e50303c849bc1cb43e4c10234dd5"
os = "macos"

    [[DGGRID7.download]]
    sha256 = "7ecdbd9a7482b4aff412f1453ac4652e0392082993e4cd451d46a943d24db46c"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.aarch64-apple-darwin.tar.gz"
[[DGGRID7]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7cacae320b82c2d878352cff2570d1975794094b"
libc = "glibc"
os = "linux"

    [[DGGRID7.download]]
    sha256 = "02b74de1d1b7635487b0ea6a794af1d02427956c78aea0f6e8aa790126823f9a"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.aarch64-linux-gnu-cxx03.tar.gz"
[[DGGRID7]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c05691a514d938c1270ca00c7c1bf0201241d482"
libc = "glibc"
os = "linux"

    [[DGGRID7.download]]
    sha256 = "de6c7fdb264003ded13b9de1ded79ebe4a566019c6b6ba84e6737ff58e8ee195"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.aarch64-linux-gnu-cxx11.tar.gz"
[[DGGRID7]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65fb30aa62ec082c6674827b10545e1585dc7f35"
libc = "musl"
os = "linux"

    [[DGGRID7.download]]
    sha256 = "6930b3286b4a68db96ce61dc37d2b481cab0fac5c9716c0b78999be86d00b0bd"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.aarch64-linux-musl-cxx03.tar.gz"
[[DGGRID7]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b93dc6e7c01065ce1dab9bd65653f0753d35c46b"
libc = "musl"
os = "linux"

    [[DGGRID7.download]]
    sha256 = "20640feb1b1ccbf46afbadb440c850b3d405cecd542ac7eb5a8e4fc8f063c07d"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.aarch64-linux-musl-cxx11.tar.gz"
[[DGGRID7]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49472a3c09adf9fb38377f7849992b355e3d6e57"
libc = "glibc"
os = "linux"

    [[DGGRID7.download]]
    sha256 = "f3e4467412d18de6840c38a3413a1315fef1feea8a1ec81138e2c50613c3ce89"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[DGGRID7]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c900d189f3a97b0da217d334e118ec723efff28b"
libc = "glibc"
os = "linux"

    [[DGGRID7.download]]
    sha256 = "b349217c19847a3925366a1f4f3c04777d1e3fca75f39097f6489eeb8aafbf85"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[DGGRID7]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fecb8262e1a8cd1673e2276a124a11145706a906"
libc = "musl"
os = "linux"

    [[DGGRID7.download]]
    sha256 = "704fe22a96e15bd18e40011c6a5067ad8ff655e698d66aee3ec8562d3bb5a580"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[DGGRID7]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "86e631fb6e06b4657259919e1bebf03aa6740f70"
libc = "musl"
os = "linux"

    [[DGGRID7.download]]
    sha256 = "7978ac83f324c7d497f7e7ae38f7bec84849b66815b96c2f2ba4bb4448ea6c2a"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[DGGRID7]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e7ed73a2f4d46e828edf6f0dd7db0aa09c5022a"
libc = "glibc"
os = "linux"

    [[DGGRID7.download]]
    sha256 = "9cd21d13c3f13c4a007f4cee33714ae4b816c4986834a760476a47953ddbd102"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[DGGRID7]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "433b56a0c7086120a852f26a7e73f638e92f03a1"
libc = "glibc"
os = "linux"

    [[DGGRID7.download]]
    sha256 = "e9a2969acfdaa1e401fa396f8705331ccc6860d98025b61848172504de25386c"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[DGGRID7]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "370f493adf71d6dc517f0014dfc0fbe2821d6ebc"
libc = "musl"
os = "linux"

    [[DGGRID7.download]]
    sha256 = "dabf01abb4c2ec782c3a60766b0a578a956a728cb912c708717d85c62b718021"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[DGGRID7]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7bc83c9fe8c47991b1ac66ed87f3ef3130b6194a"
libc = "musl"
os = "linux"

    [[DGGRID7.download]]
    sha256 = "c1b0efe23f44eac85cc22a75d02e238007f7f958371c003d7dfbf7448b5413ca"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[DGGRID7]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd9cd78fae165b44b0ad7a4e88d47a57fb99a8b1"
libc = "glibc"
os = "linux"

    [[DGGRID7.download]]
    sha256 = "0178f9e1a605a20bcc8376bc4b029c64bd2a0b88c7c83e17b4432f1726bb4d3e"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.i686-linux-gnu-cxx03.tar.gz"
[[DGGRID7]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21d240bbf023e3fe7a05378c2bb01c43a0caa446"
libc = "glibc"
os = "linux"

    [[DGGRID7.download]]
    sha256 = "3549ac2c684e9ed2d25455f49e5b7de30c5d7f27b5b89b3b7ef37164d792698e"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.i686-linux-gnu-cxx11.tar.gz"
[[DGGRID7]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e58ab65a0db141a7a31e5ec7b987c1793eb49bbd"
libc = "musl"
os = "linux"

    [[DGGRID7.download]]
    sha256 = "74615e777c2995457fd4ca4132430602904269e2248b4a8ec08cb227fb6264f5"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.i686-linux-musl-cxx03.tar.gz"
[[DGGRID7]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b4f12c0ae0de01e3fe7c8328b18d090c2a32221f"
libc = "musl"
os = "linux"

    [[DGGRID7.download]]
    sha256 = "2f6839b155735474b500fe174853d0301c70505222a179be20d5189b460c1882"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.i686-linux-musl-cxx11.tar.gz"
[[DGGRID7]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61cd41ade35cf925b011ef4b19862c3aa3933731"
os = "windows"

    [[DGGRID7.download]]
    sha256 = "ba72c63ddb9bb810ae4a58b15f019c8b188ece1c0055e2a37bafcb1f863d8046"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.i686-w64-mingw32-cxx03.tar.gz"
[[DGGRID7]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8bc4f360e1d92a043e27e5f55f65a9d367868651"
os = "windows"

    [[DGGRID7.download]]
    sha256 = "ccf4363105bff4b4ae660d80c42e4f910951043cc0f889beaa98803d6aa53c01"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.i686-w64-mingw32-cxx11.tar.gz"
[[DGGRID7]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1be5699db078931a816957452465e3b9a549538d"
libc = "glibc"
os = "linux"

    [[DGGRID7.download]]
    sha256 = "318ece64aae9dfb35a9593fc8f18ba8431c7a4f113e1a655101201da07cd1a8f"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[DGGRID7]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8314ee5f256d9d67f6faabe21db38a5549e25250"
libc = "glibc"
os = "linux"

    [[DGGRID7.download]]
    sha256 = "f4f85842516b3cfde444bf60463d96e42cd55bcecd6bda3d05db97a5f8c4753f"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[DGGRID7]]
arch = "x86_64"
git-tree-sha1 = "5bf24cc22c945db97c4e55a757e6d43e32363d87"
os = "macos"

    [[DGGRID7.download]]
    sha256 = "0848ab3f4eb6f2a1548ebc34c272d6320644e9ef0d2a4eb2bc97315aace1367d"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.x86_64-apple-darwin.tar.gz"
[[DGGRID7]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7502b1b9f9a4e87723cc7cb4716c96e1309f028b"
libc = "glibc"
os = "linux"

    [[DGGRID7.download]]
    sha256 = "a12a54f027ac12853fc3ab1b4e5c8a8a22a9e499bdb2dea24604c638e0217d52"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.x86_64-linux-gnu-cxx03.tar.gz"
[[DGGRID7]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4aac71056880a075dd62fa9b9a65d44c6de441e"
libc = "glibc"
os = "linux"

    [[DGGRID7.download]]
    sha256 = "9fda73713204db118125928632aaa1d1438f4418b2deb6022b1fd05e751c070c"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.x86_64-linux-gnu-cxx11.tar.gz"
[[DGGRID7]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5406a812858d0b19d5321ae8105bb4771543a1e"
libc = "musl"
os = "linux"

    [[DGGRID7.download]]
    sha256 = "734d43b0098c60d59bd31420da3880f92b8ff7dd41b0fefcd8917a779b2971a5"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.x86_64-linux-musl-cxx03.tar.gz"
[[DGGRID7]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a67979ce90c1f15e5d1ec17a71177c586a16a991"
libc = "musl"
os = "linux"

    [[DGGRID7.download]]
    sha256 = "25e2c4d756468501f9452f64d66ee2fb2fd7e0f731575a11bd03bd988555ae12"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.x86_64-linux-musl-cxx11.tar.gz"
[[DGGRID7]]
arch = "x86_64"
git-tree-sha1 = "34687dd3d636ab3baa0b22db77dae2335dff0819"
os = "freebsd"

    [[DGGRID7.download]]
    sha256 = "5e82226552b58f804d4fa9aac71d97e871ac359a590ef027025ea868da247c33"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.x86_64-unknown-freebsd.tar.gz"
[[DGGRID7]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "25ca4a126606148577e97002f6f1be901fa11de6"
os = "windows"

    [[DGGRID7.download]]
    sha256 = "582a9e21930c829025a1c0bea9db80ce47fca4421f28b77c05e6278573034962"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[DGGRID7]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5abd427aae7807d27a42f740825ee6500b5a5f66"
os = "windows"

    [[DGGRID7.download]]
    sha256 = "c980a226edd123deaaefec328933911d17b7cff5f9bf2398313417c7332d9fc5"
    url = "https://github.com/JuliaBinaryWrappers/DGGRID7_jll.jl/releases/download/DGGRID7-v0.9.1+0/DGGRID7.v0.9.1.x86_64-w64-mingw32-cxx11.tar.gz"
